name: ShellCheck
on: { push: { branches: [ "main" ] }, pull_request: { branches: [ "main" ] }, workflow_dispatch: {} }

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: '.'
          check_together: 'yes'
          severity: error
          additional_files: |
            src/socat-master
            debian/postinst
            debian/prerm
